# frontend/Dockerfile.frontend
FROM node:14

WORKDIR /app

COPY package.json yarn.lock ./

# Install dependencies
RUN yarn install

# Copy the rest of the application code
COPY . .

# Expose the port the app runs on
EXPOSE 8080

# Command to run the application
CMD ["yarn", "serve"]
