version: '3.8'

services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile.backend
    environment:
      - DATABASE_URL=sqlite:///./can_project.db
      - ENVIRONMENT=development
    ports:
      - "8000:8000"
    volumes:
      - ./backend:/app
    networks:
      - app-network

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile.frontend
    ports:
      - "8080:80"  # This is fine, we'll keep your original port mapping
    volumes:
      - ./frontend:/app
      - ./frontend/nginx.conf:/etc/nginx/nginx.conf:ro 
    depends_on:
      - backend
    networks:
      - app-network

networks:
  app-network:
    driver: bridge