version: '3.8'

services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile.backend
    environment:
      - DATABASE_URL=sqlite:///./can_project.db
      - ENVIRONMENT=development
    ports:
      - "8000:8000"
    volumes:
      - ./backend:/app
    command: >
      sh -c "
      if [ '$ENVIRONMENT' = 'development' ]; then
        uvicorn app.main:app --host 0.0.0.0 --port 8000 --reload;
      else
        uvicorn app.main:app --host 0.0.0.0 --port 8000;
      fi"
    networks:
      - app-network

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile.frontend
    ports:
      - "8080:80"
    volumes:
      - ./frontend:/app
    depends_on:
      - backend
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
